spring:
  datasource:
    url: jdbc:mysql://localhost/spring_data_alura?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: caelum
    
  jpa:    hibernate:      ddl-auto: update
    properties:      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL55Dialect
        

   
